//for login
export const AUTH_WATCHER = 'AUTH_WATCHER';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';

//for signup
export const SIGNUP_WATCHER = 'SIGNUP_WATCHER';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

//for forgot password
export const FORGOT_PASSWORD_WATCHER = 'FORGOT_PASSWORD_WATCHER';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';

//for logout
export const LOG_OUT_WATCHER = 'LOG_OUT_WATCHER';
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';
export const LOG_OUT_FAILURE = 'LOG_OUT_FAILURE';

//for screen loader
export const SCREEN_LOADER_START = 'SCREEN_LOADER_START';
export const SCREEN_LOADER_FINISH = 'SCREEN_LOADER_FINISH';
